### PR TITLE
changed the background of the guess_number_game and did some css fixes

### LINKED ISSUE #30: Guess the number: Enhancement
Make the game more User Interactive:
1. Changing the background which is more pleasening to eyes
2. Enhancement for dialog box which gives output for too low or high.
3. Ending of the game

### PR DESCRIPTION
**Pull request by Harsh-garg-coder**

### CODE REVIEW

**Comment by SubhojeetDas1107** [comment]
Hello @Harsh-garg-coder... I saw your new deployment and I think it still needs a few changes...
1. In mobile responsive view check the input box
2. Try to make the dialogue box (too low, too high) catchy so it will have a better UI experience

**Comment by SubhojeetDas1107** [comment]
Hello @Harsh-garg-coder... I saw your new deployment and I think it still needs a few changes...
1. In mobile responsive view check the input box
2. Try to make the dialogue box (too low, too high) catchy so it will have a better UI experience

Screenshot_20221012-222501_Chrome

**Comment by Harsh-garg-coder** [comment]
> Hello @Harsh-garg-coder... I saw your new deployment and I think it still needs a few changes...
> 
> 1. In mobile responsive view check the input box
> 2. Try to make the dialogue box (too low, too high) catchy so it will have a better UI experience
> 
> Screenshot_20221012-222501_Chrome

@SubhojeetDas1107  did the suggested changes

**Comment by SubhojeetDas1107** [comment]
A great addition indeed... Thanks for the contribution @Harsh-garg-coder

**Comment by Harsh-garg-coder** [comment]
@SubhojeetDas1107 Your Welcome

**Pull request merged**
